### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by martinobettucci** [zero01101/openOutpaint#128]
**Describe the bug**

**To Reproduce**

1. install auto1111 webui in a docker
2. install the extension for openOutpaint
3. try to use the tab

**Screenshots**
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 243, in file_deprecated
    return file(path)
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 236, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/openOutpaint/app/index.html, perhaps because it is not in any of {'/tmp/tmpevjsdp2t', '/tmp/tmp5hfsbey9', '/tmp/tmpzogxz0ia', '/tmp/tmpa7ada0s_', '/tmp/tmpbld27a32', '/tmp/tmpllpavcs4', '/tmp/tmpe5xv8afr', '/tmp/tmp__pl42yf', '/tmp/tmpulhe_bao', '/tmp/tmpcj75cgcj', '/tmp/tmpq3jyc6b1', '/tmp/tmppet837j0', '/tmp/tmpo3aod73d', '/tmp/tmp6xwco976', '/tmp/tmpcvuv7f2x', '/tmp/tmp5s8n2gl4', '/tmp/tmpaq5imlvi', '/tmp/tmp_z2pm2oc', '/tmp/tmpfroin42y', '/tmp/tmp7seq5r5v', '/tmp/tmpesmrvc04', '/tmp/tmpt8k950hh', '/tmp/tmp2y9dwinh', '/tmp/tmpfsdfabb9', '/tmp/tmpt6q2wyvu', '/tmp/tmpgjt1akdu', '/tmp/tmpimncjgmy', '/tmp/tmpjy7fx3uu', '/tmp/tmp1m74wn_q', '/tmp/tmpv2a0jmaz', '/tmp/tmpff68dlnz', '/tmp/tmpqhtgurr7', '/tmp/tmp7t2bhx37', '/tmp/tmp91q98u4t', '/tmp/tmpf8rsxz6k', '/tmp/tmp0qmfshmo', '/tmp/tmp3c4b_sgy', '/tmp/tmptxk2ly50', '/tmp/tmpbkskttw6', '/tmp/tmpw_hpttf3', '/tmp/tmptvp40g3j', '/tmp/tmp5t5jq7a9', '/tmp/tmphxegihkn', '/tmp/tmp74a3jswd', '/tmp/tmp1mk9ajrk', '/tmp/tmpb5r656vc', '/tmp/tmpjl7t73zk', '/tmp/tmpivtdt05r', '/tmp/tmpva0oxk9k', '/tmp/tmpc1s4qjiy', '/tmp/tmperbdztcn', '/tmp/tmpjqzbir31', '/tmp/tmp92vttral', '/tmp/tmp5pc474lx', '/tmp/tmp1b8fo8bi'}

**Desktop (please complete the following information):**
- Env: docker for nvidia cuda 11.6
- OS and Version: [e.g. iOS 15, win10x64 v22h2, palmOS 3]
- GPU: RTX2070Super
- Browser: chrome

**Comment by seijihariki** [comment]
Hi! Could you provide the Dockerfile used for this? And the command used to start the container?

**Comment by changhefirst** [comment]
I have the same error. The docker file is from here: https://github.com/AbdBarho/stable-diffusion-webui-docker/

Installed Openoutpaint extension from Extensions tag of AUTOMATIC1111 automately.  Unselected openOutpaint-webUI-extension and restart UI, then errors gone.

Could you please provide a docker file for Openoutpaint? If Openoutpaint run independely in docker, then it may switch the connection of my local docker SD webui and my colab SD webui.

> webui-docker-auto-1  | ERROR:    Exception in ASGI application
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
webui-docker-auto-1  |     result = await app(  # type: ignore[func-returns-value]
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
webui-docker-auto-1  |     return await self.app(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
webui-docker-auto-1  |     await super().__call__(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
webui-docker-auto-1  |     await self.middleware_stack(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
webui-docker-auto-1  |     raise exc
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
webui-docker-auto-1  |     await self.app(scope, receive, _send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
webui-docker-auto-1  |     await responder(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
webui-docker-auto-1  |     await self.app(scope, receive, self.send_with_gzip)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
webui-docker-auto-1  |     await self.app(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
webui-docker-auto-1  |     raise exc
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
webui-docker-auto-1  |     await self.app(scope, receive, sender)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
webui-docker-auto-1  |     raise e
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
webui-docker-auto-1  |     await self.app(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
webui-docker-auto-1  |     await route.handle(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
webui-docker-auto-1  |     await self.app(scope, receive, send)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
webui-docker-auto-1  |     response = await func(request)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
webui-docker-auto-1  |     raw_response = await run_endpoint_function(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
webui-docker-auto-1  |     return await run_in_threadpool(dependant.call, **values)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
webui-docker-auto-1  |     return await anyio.to_thread.run_sync(func, *args)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
webui-docker-auto-1  |     return await get_asynclib().run_sync_in_worker_thread(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
webui-docker-auto-1  |     return await future
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
webui-docker-auto-1  |     result = context.run(func, *args)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 243, in file_deprecated
webui-docker-auto-1  |     return file(path)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 236, in file
webui-docker-auto-1  |     raise ValueError(
webui-docker-auto-1  | ValueError: File cannot be fetched: extensions/openOutpaint-webUI-extension/app/index.html, perhaps because it is not in any of {'/tmp/tmpmfkgtn9e', '/tmp/tmp7e6rjsin', '/tmp/tmpfep_ww7w', '/tmp/tmps7l67dyh', '/tmp/tmp3vmqgc5n', '/tmp/tmprrjw8chc', '/tmp/tmpy268farm', '/tmp/tmppmvl5on6', '/tmp/tmprptpy3nk', '/tmp/tmpznim6pvj', '/tmp/tmpwogqnn_0', '/tmp/tmpolsumrdk', '/tmp/tmpvrpb5abe', '/tmp/tmpch42g7y7', '/tmp/tmp8f4p7g0w', '/tmp/tmpgulnb21k', '/tmp/tmpjb9fo22i', '/tmp/tmprlz0eejo', '/tmp/tmpy3ydtwoo', '/tmp/tmpub5vnry9', '/tmp/tmphaq1oas3'}

**Comment by seijihariki** [comment]
@changhefirst thank you! Could you verify for me if other extensions such as image browser and dreambooth work?

**Comment by seijihariki** [comment]
Also, a Dockerfile for openOutpaint would be as simple as a base Apache2 alpine  container copying openOutpaint to the web directory.

**Comment by seijihariki** [comment]
So, the issue seems to be that the extensions directory is a symbolic link in the container.

![image](https://user-images.githubusercontent.com/7552751/209902832-ea0aed9c-b9b7-44c9-bf6a-634dd4904e9d.png)

This causes the `/file/` route to access the extensions file as an external source:

![image](https://user-images.githubusercontent.com/7552751/209902986-349b12b9-ed78-4af8-a898-e3a2ed90851e.png)

And gradio blocks the access, as it is not inside the webui directory. Not really sure how we could solve this, as basic file hosting access is a basic requirement for the openOutpaint extension, and the routes.py file does not seem to have a bypass for this behavior:
![image](https://user-images.githubusercontent.com/7552751/209903480-4e07e9e5-0b3a-43c6-90f5-7a51e096b600.png)
As we can see in the selection, only `cwd` and temp dirs are accepted as valid  `file` origins.

Currently, a workaround would be to remove the volume link manually:

![image](https://user-images.githubusercontent.com/7552751/209903628-71c8e7fb-3948-4345-b179-40abfada61ef.png)

But in this case, extension volume persistence is lost, and creating a new container will not retain installed extensions. For normal user usage this should be enough for now...

Another workaround would be to change docker compose to mount the `extensions` folder directly. But I think in this case that it would be too big an architectural change of the docker compose file itself...

So, for now, @changhefirst and @martinobettucci, you can try doing the following:
![image](https://user-images.githubusercontent.com/7552751/209904281-2a61b585-8584-44b2-b8c5-dfe84b56d26c.png)

Changing this part of `entrypoint.sh` to:
```bash
#MOUNTS["${ROOT}/extensions"]="/data/config/auto/extensions"
if [[ -f "${ROOT}/extensions" ]]
then
  rm "${ROOT}/extensions"
  mkdir "${ROOT}/extensions" 
fi
```

and running a `docker-compose up --build auto` once. (Must not run it again, or else container and extensions will probably reset)

However, this will remove currently installed extensions, and if you have to recreate the container (for Dockerfile updates, for example), extensions will not be kept.

We would need to contact the developers of the https://github.com/AbdBarho/stable-diffusion-webui-docker/ repo to reach a more reasonable compromise... Will mark this as external, as we can't really do much to fix this for now.

**Comment by seijihariki** [comment]
Also, this seems to be an extension-only issue, so will be moving this issue to the extension repo.
