### ISSUE TITLE
[Bug]: ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by wilzamguerrero** [zero01101/openOutpaint#210]
### What happened?

Running on public URL: https://73062440-2dd8-46db.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Startup time: 84.3s (import gradio: 3.2s, import ldm: 6.6s, other imports: 3.3s, list extensions: 1.2s, load scripts: 1.8s, load SD checkpoint: 40.2s, create ui: 17.0s, gradio launch: 10.9s, scripts app_started_callback: 0.2s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 120, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/content/stable-diffusion-webui/modules/api/api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 716, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 255, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> sd_checkpoint_hash
  value is not None (type=type_error.not_none)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ... [etc]

### What should have happened?

Hi thanks for this tool well the problem is that i use google colab, i add --api and --cors-allow-origins=https://zero01101.github.io" and i try with --cors-allow-origins=https://zero01101.github.io/openOutpaint/ and i paste the gradio link in https://zero01101.github.io/openOutpaint and when i try to use i have this error in colab

### Commit where the problem happens

.

### What platforms do you use to access openOutpaint?

Other/Cloud

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

.

### AUTOMATIC1111 webUI Commandline Arguments

--api and --cors-allow-origins=

### Additional information
i have the same error with the extension  web ui

**Comment by zero01101** [comment]
so i gotta admit almost zero familiarity with colabs beyond just booting it up and making sure it worked, but i see a ton of python 3.9 in those logs, and i'm certain [A1111 requires 3.10.6 specifically](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-NVidia-GPUs) so i don't know if that might have something to do with it?

i also don't know which colab notebook you're using, but i guess [TheLastBen](https://github.com/TheLastBen/fast-stable-diffusion)'s is generally the "most compatible"?

**Comment by zero01101** [comment]
closing as stale
